  var elChild = document.getElementById('elChild');

  $(document).ready(function() {
    $('[class^="zipclick"]').on('click', function(e) {
      
      var zipCode = $(this).attr('id');
      console.log(zipCode);
      numberZipCode =parseInt(zipCode);
      console.log(numberZipCode);

      switch (numberZipCode) {
case 75050: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1w-S6gCaj_4kBfkCAzwR9dU2yfu8" width="100%" height="480"></iframe>'; break;
case 75051: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1_D4-xnaXSPKzx7mllISBRDiyJTI" width="100%" height="480"></iframe>'; break;
case 75052: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1IrKCoWGy2wrd2OWqRPp-qFJMb7M" width="100%" height="480"></iframe>'; break;
case 75052: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1-mXCnGBUWdHDcuN-zkEwo8IemsQ" width="100%" height="480"></iframe>'; break;
case 75054: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1Q6GxhvdEJQWTQtzIRqj_xNaNwD8" width="100%" height="480"></iframe>'; break;
case 75054: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1AC11WNb7in3f_cqWoxMPApTGqBc" width="100%" height="480"></iframe>'; break;
case 76001: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1yjuVqx3e9uDATFyQLhMUg4DTYCU" width="100%" height="480"></iframe>'; break;
case 76001: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1kaKxd-3iTFchKWZlcF5HmpFBlUo" width="100%" height="480"></iframe>'; break;
case 76002: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1y0DvWINReaMfw1YFF65stxnemm4" width="100%" height="480"></iframe>'; break;
case 76006: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1KBJWPH6FPOPqCzzsjxlnFN0y34Y" width="100%" height="480"></iframe>'; break;
case 76008: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1TVx4X87Xz7W4SWE-4BLhDYLu_V4" width="100%" height="480"></iframe>'; break;
case 76010: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1eFS-J81-811_wbBERL6zx7xgXeY" width="100%" height="480"></iframe>'; break;
case 76011: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1bHmwJqCMKcHim6B3aH-EUE2kpnc" width="100%" height="480"></iframe>'; break;
case 76012: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1iw8JMWUfRlegnuxEN9BnU_NDvRc" width="100%" height="480"></iframe>'; break;
case 76013: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1CHj4f2fbTVxMs-ql4nSV4sQWfzE" width="100%" height="480"></iframe>'; break;
case 76014: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=10Yqi2GPSIEYL2QX9Py_xJfl2BUA" width="100%" height="480"></iframe>'; break;
case 76015: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1g40t-aSPd7-lMZOww2_iVkXCf_c" width="100%" height="480"></iframe>'; break;
case 76016: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1VUp4TYhUhPLqjm2_WR_vZ29rBtA" width="100%" height="480"></iframe>'; break;
case 76017: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=16xZrgr0hnA51FYhffsPMSh1o7Jg" width="100%" height="480"></iframe>'; break;
case 76018: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1X0rxXlrQZdsUdhw3SMx9FcA4tsw" width="100%" height="480"></iframe>'; break;
case 76020: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1LPa3ZX5Z71IaNUHMoISqqXAXxNE" width="100%" height="480"></iframe>'; break;
case 76021: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1lvj2iBBuAB8vnZ3iIOZD5WtRQ1c" width="100%" height="480"></iframe>'; break;
case 76022: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1tG10wRm_t2P5BPTP7or2Nw2uLtI" width="100%" height="480"></iframe>'; break;
case 76028: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=13Ni4RkSBPJi12HIvWk5MHoAJWho" width="100%" height="480"></iframe>'; break;
case 76034: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1X0_UaGZI8P50WZEG-hr1YYyw4Ck" width="100%" height="480"></iframe>'; break;
case 76036: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1nerTk-BvBAh1YMLW8im9A9lKOK8" width="100%" height="480"></iframe>'; break;
case 76039: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=18h_MxvOBZAPC_VPSqBr-ndUK_wM" width="100%" height="480"></iframe>'; break;
case 76040: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1CBABOzf0ht-b0Fy_d0NqxV8t5Cg" width="100%" height="480"></iframe>'; break;
case 76051: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=18iarnFPmIgjbfAeFzKu6e3_0WeQ" width="100%" height="480"></iframe>'; break;
case 76052: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1sJyjPNE9he_1a9eIYm-kwtqzPqo" width="100%" height="480"></iframe>'; break;
case 76053: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1i1iKrvCVfyOJsDdImezzEKCHfdg" width="100%" height="480"></iframe>'; break;
case 76054: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=17_oVGoQfjWs-vlKEi83uNpHZmAs" width="100%" height="480"></iframe>'; break;
case 76060: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1hccEsP-3Dvr39u4snFKACIUEkNQ" width="100%" height="480"></iframe>'; break;
case 76063: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1XexdkmImQTOFgEMnflrs42vmirw" width="100%" height="480"></iframe>'; break;
case 76071: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1oZ3ygsysH1aLov0JkozQgmTqVFI" width="100%" height="480"></iframe>'; break;
case 76092: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1z5PFKEiatHRobxYNpKgxxIuTBzI" width="100%" height="480"></iframe>'; break;
case 76102: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1fTysRvfMT_zT73nomT_e6XNxP-k" width="100%" height="480"></iframe>'; break;
case 76103: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1BA3x5UMpCtBlbwi3Gw87Q8bC4PU" width="100%" height="480"></iframe>'; break;
case 76104: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1hucDD_jdcrnduPT3-gvoyjpHT2E" width="100%" height="480"></iframe>'; break;
case 76105: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=17g0JDP_9i3THIjX7cn5N5DkxIaw" width="100%" height="480"></iframe>'; break;
case 76106: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1xEyEIAurfe33W86yByFBNd8B0yU" width="100%" height="480"></iframe>'; break;
case 76107: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1Sv8FJ5tLp6gemSp_3LHZwc_llRY" width="100%" height="480"></iframe>'; break;
case 76108: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1xTERrflC6Az0JbpgRDT_qkPUWyo" width="100%" height="480"></iframe>'; break;
case 76109: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1QlYqQOKFwrgzQr5NI7v5GryYTc4" width="100%" height="480"></iframe>'; break;
case 76110: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1Ft_GiYiyKmeOYC1AGophdKoAj9I" width="100%" height="480"></iframe>'; break;
case 76111: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1xTiQfXsohCcYbSeVPMVlNWFABHo" width="100%" height="480"></iframe>'; break;
case 76112: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1vfzFf3Z3Fvj2zeKDm3zMLWvqPG8" width="100%" height="480"></iframe>'; break;
case 76114: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1cBljFk43arsBuklWrjo9kl-SMK0" width="100%" height="480"></iframe>'; break;
case 76115: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1KQEuUoPv2i7hoz4DKJwRo7PKdlo" width="100%" height="480"></iframe>'; break;
case 76116: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=11aT8jIY1k3GjlNfTNPSTRIbQF4U" width="100%" height="480"></iframe>'; break;
case 76117: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1-l93Yc3aXCVE0qL9lDzCZOb910Y" width="100%" height="480"></iframe>'; break;
case 76118: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1VJpT_UWBEQdCy8BhdbFuFZjaVhU" width="100%" height="480"></iframe>'; break;
case 76119: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1N6hR5eDyOZdk0nnI0F2fyyL72dw" width="100%" height="480"></iframe>'; break;
case 76120: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1s6m5LjQIAIOrj7w2sVDWFXuFwcY" width="100%" height="480"></iframe>'; break;
case 76123: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=16QQkKZMdqvvgGZm6dXcrMWD42dM" width="100%" height="480"></iframe>'; break;
case 76126: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=14fUYEiYvW5HnP28Qg3_ZNJUvt6Y" width="100%" height="480"></iframe>'; break;
case 76131: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1NNRMDtW_fKnPvpdGiYc2tSqlgPw" width="100%" height="480"></iframe>'; break;
case 76132: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1LyHAYOk5BZta3CSXf1APrkbyTUU" width="100%" height="480"></iframe>'; break;
case 76133: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1u97oVyxQXKgk4Y5mreDsYN_KxhU" width="100%" height="480"></iframe>'; break;
case 76134: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1r7_VHbUht2sOIyAXxfHU31Izf20" width="100%" height="480"></iframe>'; break;
case 76135: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1K7Ci_l13JcLjpYnDmRBVY1Yhy60" width="100%" height="480"></iframe>'; break;
case 76137: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1hH54rT54cFICpabLELb885Ru7PI" width="100%" height="480"></iframe>'; break;
case 76137: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1TcYZd2tkw3wxXyo6kYVpred9J1M" width="100%" height="480"></iframe>'; break;
case 76140: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=14mt94_rypGc7PdclJHN_XXrlBDA" width="100%" height="480"></iframe>'; break;
case 76148: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=14mt94_rypGc7PdclJHN_XXrlBDA" width="100%" height="480"></iframe>'; break;
case 76155: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1Nx7vjgt7TIVaP5usDYupfUWrbIk" width="100%" height="480"></iframe>'; break;
case 76164: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1y1J_kDwc8KSIBDd60O7fuMg3BKs" width="100%" height="480"></iframe>'; break;
case 76177: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1c680ip_tB8MRfgs6SzpGyfaMFqE" width="100%" height="480"></iframe>'; break;
case 76179: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=119qHpA5rYuV0kKXhpBafbxeBKjA" width="100%" height="480"></iframe>'; break;
case 76179: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1Rw30cwvD_U0QRgHBwr8EOvvKvlE" width="100%" height="480"></iframe>'; break;
case 76180: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=10Rhlt46Na6vPX06LU_22k1pN0ys" width="100%" height="480"></iframe>'; break;
case 76182: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=18zyLzDT3SPfnd1aWqIrpuW_Zlz8" width="100%" height="480"></iframe>'; break;
case 76244: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=18KZUO5pExChpFEd-9CnQYebJTQ0" width="100%" height="480"></iframe>'; break;
case 76248: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1Dd5HEQMxWei7AL1Tcf7cvjwFwm8" width="100%" height="480"></iframe>'; break;
case 76248: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1QGBFq6JGUvr5KjhL1gJAoMTVI_I" width="100%" height="480"></iframe>'; break;
case 76262: elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1DiWqzsP5Gtrv3u7mvdv1Kh10QEw" width="100%" height="480"></iframe>'; break;
case "Addison": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1zdtzwB95cduvs6d-s261nFEsZsA" width="100%" height="480"></iframe>'; break;
case "Balch Springs": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1TPjpGkYY2N1SzykkvOG7Xw4_X-U" width="100%" height="480"></iframe>'; break;
case "Carrollton": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1-QpSUeREFT31ZW1vIkaSTOWl0pE" width="100%" height="480"></iframe>'; break;
case "Cedar Hill": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1ZpelTZpboJiyybFj31JRB3Bnel8" width="100%" height="480"></iframe>'; break;
case "Coppell": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=157NLdN_SxGFEww9YByzYZIPjXkY" width="100%" height="480"></iframe>'; break;
case "Desoto": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1iqfR3jBo7wJGhMVGMBNoZgu1wOs" width="100%" height="480"></iframe>'; break;
case "Duncanville": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1toa9cnE9zGaAG8NgHFZ5YhjxDrw" width="100%" height="480"></iframe>'; break;
case "Farmers Branch": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=12NU_PerOjgKDuS_7umSk23C3Vcs" width="100%" height="480"></iframe>'; break;
case "Garland": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=16C1hjq-D1ywN_7cW7-UiH3OPvOQ" width="100%" height="480"></iframe>'; break;
case "Glenn Heights": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1FPVQCC-Qm6Z8dT81N_fYkI8uYHU" width="100%" height="480"></iframe>'; break;
case "Grand Praire": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1EsSqEYpmA9MacHf763piYwP1Qjk" width="100%" height="480"></iframe>'; break;
case "Highland Park": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1w5bmfsdYUHc3TMW9webL1z-MO70" width="100%" height="480"></iframe>'; break;
case "Irving": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1YtKvtcF9I66Rm0vCOwKKrSb-F5g" width="100%" height="480"></iframe>'; break;
case "Lancaster": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1qwJiMW2UlTHz_Go1MU42ZXvo7eA" width="100%" height="480"></iframe>'; break;
case "Mesquite": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=19pfWRpqcnXFdYzpMxhycjlD8L1w" width="100%" height="480"></iframe>'; break;
case "Richardson": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1Yjx1Pinh1ZWUPiW3MWC-RAE6hgY" width="100%" height="480"></iframe>'; break;
case "Rowlett": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=15kKIhTrOdWqt0TR4ef9R4VyVRdg" width="100%" height="480"></iframe>'; break;
case "Sachse": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=18OtMVk2d_TQJ2CHUwqv-midJHeM" width="100%" height="480"></iframe>'; break;
case "Seagoville": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1d2SBPEHK2Um7O3ZXLRyWheISU5o" width="100%" height="480"></iframe>'; break;
case "Sunnyvale": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1I6R9SlTLWegjKY4YctCDDhvBXLE" width="100%" height="480"></iframe>'; break;
case "University Park": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1L8JjJM-SpETdk9ahwnQu2peK8vM" width="100%" height="480"></iframe>'; break;
case "Wilmer": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=15nTRv9TFNPd9OgYaaNCarRP1KVI" width="100%" height="480"></iframe>'; break;
case "Wylie": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1kz-sGu5U9LBOkBK2nKEs2oGMAZE" width="100%" height="480"></iframe>'; break;
case "Dallas": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1McxhpQtjW5oRqeIolSz3c5MD9jM" width="100%" height="480"></iframe>'; break;
case "Allen": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1r5guj-oPgGMUm4cbiHDn5KFsUD8" width="100%" height="480"></iframe>'; break;
case "Anna": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1r11pyPimJlT9QRLjQLVA3ZX-9YA" width="100%" height="480"></iframe>'; break;
case "Blue Ridge": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1QkEhsWy8ohjNem2DQcIGRtuaFmw" width="100%" height="480"></iframe>'; break;
case "Carrollton_Collin": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1FszhWTBOM0bBB-D4WXT3EPYzBJg" width="100%" height="480"></iframe>'; break;
case "Celina": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1LJZsTi9sV-i4PHSqTTJq0jx2-fc" width="100%" height="480"></iframe>'; break;
case "Dallas_Collin": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1LCsobj1LnNMbqEVJ1PsOee7-Mhk" width="100%" height="480"></iframe>'; break;
case "Fairview": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1sSaBs1XcL9j0LsD_a069hUc1rCI" width="100%" height="480"></iframe>'; break;
case "Farmersville": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1klMiDJfBrocSMDihUic3EqqbC2g" width="100%" height="480"></iframe>'; break;
case "Frisco": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1DGMQxzTVMyDFA_Fo3ia5Y2q2fUE" width="100%" height="480"></iframe>'; break;
case "Garland_Collin": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1BdQhLbA9vbnkQVTj8SOBws9aRKQ" width="100%" height="480"></iframe>'; break;
case "Josephine": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1op2nxtKf0RepLQ_areq98bs4Y0M" width="100%" height="480"></iframe>'; break;
case "Lavon": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1w7tg2n7eXiaqxXjjXvQW203Pz1A" width="100%" height="480"></iframe>'; break;
case "Lucas": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1f36XMGB5_cYqIjRWF7amk0zcVs4" width="100%" height="480"></iframe>'; break;
case "McKinney": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1emmdC83sEO0-7ZSgmTJFKN3P_JA" width="100%" height="480"></iframe>'; break;
case "Melissa": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1cZNcRKYF3gRSS__rvQo-7roRDO0" width="100%" height="480"></iframe>'; break;
case "Murphy": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1zq8PInSu5WvhPKprLOw2wx4E2sM" width="100%" height="480"></iframe>'; break;
case "Nevada": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=144ElM4NkKemJqqMinm_Qrcl_ILQ" width="100%" height="480"></iframe>'; break;
case "Parker": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1K5LFDmXi9hLC3sEEVXlevvEVnKs" width="100%" height="480"></iframe>'; break;
case "Plano": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=11-SNXRJkIf09FsgpKoE6gtsQVkk" width="100%" height="480"></iframe>'; break;
case "Princeton": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1vK4bQYylUSIIek4x5_a7BpdSeBg" width="100%" height="480"></iframe>'; break;
case "Prosper": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1rdoPHuDu0Us4VbuYsci_FXzYsYQ" width="100%" height="480"></iframe>'; break;
case "Richardson_Collin": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1Yzu_ENaBSWWevnuS9GXrB8ZnMos" width="100%" height="480"></iframe>'; break;
case "Royse": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1cxIimQqJZWP47Z7EPrX1HSHT1vg" width="100%" height="480"></iframe>'; break;
case "Sachse_Collin": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1KOQG5_bG7qQwQXA890Om5w8J5SA" width="100%" height="480"></iframe>'; break;
case "St. Paul": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1b-3MYxSZ9E2ZUj0LDxF4EPSEmSA" width="100%" height="480"></iframe>'; break;
case "Wylie_Collin": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1kE2OxYEp2YnwHC5Xr9nxbxGVeAw" width="100%" height="480"></iframe>'; break;
case "Argyle": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1ZwsPFtvKmvaWcCLgvywAT06jJSw" width="100%" height="480"></iframe>'; break;
case "Aubrey": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1M2wLuGUVsWJT76S_gJhvuFJZtwI" width="100%" height="480"></iframe>'; break;
case "Bartonville": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1WAXeDzEPpQ0Mwpfdkl8Vs0JYTVg" width="100%" height="480"></iframe>'; break;
case "Carrollton_Denton": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1Baj6UUZxrXz-2dnAyIL3VklZCQ0" width="100%" height="480"></iframe>'; break;
case "Coppell": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1drOULdpTuaAR3HSxX5UjJRJTdlU" width="100%" height="480"></iframe>'; break;
case "Copper Canyon": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=18wiEMvMzuJOZBzWUxQGrajRmCA4" width="100%" height="480"></iframe>'; break;
case "Corinth": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1Quaf_S9-RVQ4HkKGqW7dSrCzdng" width="100%" height="480"></iframe>'; break;
case "Cross Roads": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1pTY7akgHqlFTGO4bRwFoN6V7W3M" width="100%" height="480"></iframe>'; break;
case "Dallas": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1QYN6WA60NYyvLuG4SyhiSJ7PIiA" width="100%" height="480"></iframe>'; break;
case "Denton": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1-HqgZuqAjV1p_mvvKNxZ8mHe7s0" width="100%" height="480"></iframe>'; break;
case "Double Oak": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1ad2vpOhy4Zki8CtzAFayuiZ1e_Q" width="100%" height="480"></iframe>'; break;
case "Flower Mound": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1xkr8g6DfE795pw1__N9_mCvjMWU" width="100%" height="480"></iframe>'; break;
case "Forth Worth": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1_ydmP9ED9d_ENe9cBSOF856ZTRk" width="100%" height="480"></iframe>'; break;
case "Frisco": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1IoqkyGkVwrHfuywev_rnIfbNx4E" width="100%" height="480"></iframe>'; break;
case "Hickory Creek": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1q4pDqbTOU2iIvqgUHKu6FzTKFR0" width="100%" height="480"></iframe>'; break;
case "Highland Village": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1PsXG_vwUQS4-8BGZM9_qOkOuAl8" width="100%" height="480"></iframe>'; break;
case "Justin": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1BW3xWLQR_6wT9o9HRi8ZqYivXwc" width="100%" height="480"></iframe>'; break;
case "Krugerville": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1pW_BRXLP70racUlcfoEt6Vrhi2c" width="100%" height="480"></iframe>'; break;
case "Krum": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1e58goTrAICxboUqFp-dCZmbgZ64" width="100%" height="480"></iframe>'; break;
case "Lake Dallas": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1yxsMIyBiYx_ySrLleIAczeTqQ6M" width="100%" height="480"></iframe>'; break;
case "Lakewood Village": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1Va6uK9PTZ6yvKIHVOguC1yASW8o" width="100%" height="480"></iframe>'; break;
case "Lewisville": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=18qqlAiTb-6vWpcUhwWRVHvTi0nY" width="100%" height="480"></iframe>'; break;
case "Little Elm": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1yl1OtvuiyVVz1mADDxTXCf0J_Ic" width="100%" height="480"></iframe>'; break;
case "Northlake": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1513jo4D5tHFoJLCSATizGJd9Hn0" width="100%" height="480"></iframe>'; break;
case "Oak Point": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1C2GtHam0k9gG8n17keXE18PzSUg" width="100%" height="480"></iframe>'; break;
case "Pilot Point": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=15eq2Gqp7sFArk9mbDvOud91lhmA" width="100%" height="480"></iframe>'; break;
case "Plano": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1LE6Z7eeOzNElci4n0mhFsbK7sXk" width="100%" height="480"></iframe>'; break;
case "Ponder": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1JB5CAzgLyWq8OgWGluoQ-9lgfoA" width="100%" height="480"></iframe>'; break;
case "Prosper": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1sZverpfvgTM0GDTF2WWNKtFuIAs" width="100%" height="480"></iframe>'; break;
case "Providence": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=19LwIpplCAinZCQl98ru_152jfqw" width="100%" height="480"></iframe>'; break;
case "Roanoke": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1nkpHEc15abViQrEucwGrgvtFoGs" width="100%" height="480"></iframe>'; break;
case "Shady Shores": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1iyGeA3NSGipA8FmbvbC5vWld3wk" width="100%" height="480"></iframe>'; break;
case "Southlake": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1ZGKRwLBzMEWSRc_Ib2vyHH_GHNM" width="100%" height="480"></iframe>'; break;
case "The Colony": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1FPU7Ydur0uzXySctM5QiMcvA404" width="100%" height="480"></iframe>'; break;
case "Trophy Club": elChild.innerHTML = '<iframe src="https://www.google.com/maps/d/embed?mid=1mFb9a9jcyNiWr2fPu1_OVwRjwLA" width="100%" height="480"></iframe>'; break;
default: elChild.innerHTML = '<p>try again</p>';
break;


      }
      
      
    });
  });
